version: '3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql